const defaultValues = {
  name1: '',
  lastName1: '',
  RutPlayer1: '',
  email1: '',
  mobileNumber1: '',
  birthDate1: '',
  poloSize1: '',
  category1: '',
  clubPlay1: '',
  positionPlay1: '',
  medicalProblem1: '',
  name2: '',
  lastName2: '',
  RutPlayer2: '',
  email2: '',
  mobileNumber2: '',
  birthDate2: '',
  poloSize2: '',
  category2: '',
  clubPlay2: '',
  positionPlay2: '',
  medicalProblem2: '',
  discountCoupon: '',
};
export default defaultValues;
